
person:
  name: ordo
  age: 3
  happy: false
  birth: 2000/01/01
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - girl
    - music
  dog:
    name: 旺财
    age: 1
server:
  port: 8080
spring:
  profiles:
    active: dev
---
person:
  name: ordo@163.com
  age: 3
  happy: false
  birth: 2000/01/01
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - girl
    - music
  dog:
    name: 旺财
    age: 1
server:
  port: 8081

spring:
  profiles:
    active: test
